services:
  postgres:
    image: postgres:16-alpine
    container_name: gogoskola_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gogoskola_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c max_connections=300 -c shared_buffers=1GB -c effective_cache_size=3GB -c work_mem=32MB -c maintenance_work_mem=256MB
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 3072M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gogoskola_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  bun-api:
    build:
      context: ./bun-api
      dockerfile: Dockerfile
    container_name: gogoskola_bun
    profiles:
      - bun
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/gogoskola_db
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4096M

  dotnet-api:
    build:
      context: ./dotnet-api
      dockerfile: Dockerfile
    container_name: gogoskola_dotnet
    profiles:
      - dotnet
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/gogoskola_db
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4096M

  laravel-api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: gogoskola_laravel
    profiles:
      - laravel
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: "base64:qCLOTkcTBQ1lMeO9Ye3D3Pdgm8ls8jI0uUJcyjx2o8Y="
      PORT: 3000
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: gogoskola_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4096M

volumes:
  pgdata:
